# Generated by Django 4.1.7 on 2023-03-03 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Brand')),
            ],
            options={
                'verbose_name': 'car brand',
                'verbose_name_plural': 'Car brands',
            },
        ),
        migrations.CreateModel(
            name='CarColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Color')),
            ],
            options={
                'verbose_name': 'car color',
                'verbose_name_plural': 'Car colors',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(unique=True, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='Full name')),
                ('role', models.CharField(choices=[('client', 'client'), ('seller', 'seller')], default='client', max_length=15, verbose_name='User status')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('ar', 'Arab'), ('he', 'Hebrew')], default='ru', max_length=3)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='CarOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steering_wheel_position', models.CharField(choices=[('left', 'left'), ('right', 'right')], max_length=15, verbose_name='Steering wheel position')),
                ('some_wishes', models.TextField(null=True, verbose_name='Wishes to order')),
                ('order_status', models.CharField(choices=[('open', 'open'), ('in progress', 'in progress'), ('close', 'close')], default='open', max_length=15, verbose_name='Order status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('car_brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars_sales.carbrand', verbose_name='Car brand')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars_sales.carcolor', verbose_name='Car color')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer', to='cars_sales.user', verbose_name='Customer')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seller', to='cars_sales.user', verbose_name='Seller')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'Orders',
                'ordering': ['created_at'],
            },
        ),
    ]
