# Generated by Django 4.1.7 on 2023-03-10 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Brand')),
            ],
            options={
                'verbose_name': 'car brand',
                'verbose_name_plural': 'Car brands',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Model')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars_sales.carbrand', verbose_name='Brand')),
            ],
            options={
                'verbose_name': 'car model',
                'verbose_name_plural': 'Car models',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(unique=True, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='Full name')),
                ('role', models.CharField(choices=[('client', 'client'), ('seller', 'seller')], default='client', max_length=15, verbose_name='User status')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('ar', 'Arab'), ('he', 'Hebrew')], default='ru', max_length=3)),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Registration date')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='CarOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('some_wishes', models.TextField(null=True, verbose_name='Wishes to order')),
                ('order_status', models.CharField(choices=[('open', 'open'), ('in progress', 'in progress'), ('close', 'close')], default='open', max_length=15, verbose_name='Order status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars_sales.carmodel', verbose_name='Car')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='cars_sales.user', verbose_name='Customer')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller', to='cars_sales.user', verbose_name='Seller')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'Orders',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarModelPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Photo')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars_sales.carmodel')),
            ],
            options={
                'verbose_name': 'car model photo',
                'verbose_name_plural': 'Car model photos',
            },
        ),
    ]
