# Generated by Django 4.1.7 on 2023-03-04 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars_sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carorder',
            name='car_brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars_sales.carbrand', verbose_name='Car brand'),
        ),
        migrations.AlterField(
            model_name='carorder',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars_sales.carcolor', verbose_name='Car color'),
        ),
    ]
