# Generated by Django 4.1.7 on 2023-03-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='description',
            field=models.TextField(default='', null=True, verbose_name='Description'),
        ),
    ]
