# Generated by Django 4.1.7 on 2023-03-09 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars_sales', '0002_alter_carorder_car_brand_alter_carorder_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carorder',
            name='steering_wheel_position',
        ),
    ]
