# Generated by Django 4.1.7 on 2023-03-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_sales', '0003_alter_carmodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
