# Generated by Django 4.1.7 on 2023-03-10 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars_sales', '0005_alter_carorder_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carorder',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller', to='cars_sales.user', verbose_name='Seller'),
        ),
    ]
